#!/usr/bin/env bash
# aggregator-stub.sh
# Phase 1 T5 산출물 (paper-autopilot v1.1.0-alpha)
# Defensive SPOF insurance per plan-eng-review 1.1A 결정
#
# Purpose:
#   9 aw-* reviewer agent의 결과 JSON list를 input으로 받아서
#   aw-prose-polisher가 input으로 받을 수 있는 포맷으로 변환.
#   polisher가 직접 9-reviewer JSON aggregation을 못 받을 경우 보험.
#
# Usage:
#   ./aggregator-stub.sh --input <reviewer_results_dir> --output <polisher_input.md>
#   reviewer_results_dir: 각 reviewer가 result.json을 쓴 디렉토리
#     예: reviewer_results/aw-claim-validator.json, aw-move-flow.json, ...
#   polisher_input.md: polisher에 inject할 markdown (text + 5 dim 채점 요약)
#
# Schema (reviewer result.json):
#   {
#     "reviewer": "aw-claim-validator",
#     "dim": "completeness",
#     "score": 0-10,
#     "verdict": "BLOCK" | "WARN" | "PASS",
#     "findings": [
#       {"severity": "BLOCK|WARN|MINOR", "location": "line N", "description": "..."}
#     ]
#   }
#
# Output (polisher_input.md):
#   markdown text containing:
#   - ## Original artifact (PRD/SOP/manuscript draft 원본)
#   - ## Review Aggregation
#     - 각 dim별 점수 + BLOCK list
#   - ## Polish Targets
#     - BLOCK+WARN findings를 location 순으로 정렬, polisher가 fix할 대상

set -euo pipefail

# ─── cross-platform tmpdir ───
TMPDIR="${TMPDIR:-/tmp}"

# ─── arg parse ───
INPUT_DIR=""
OUTPUT_FILE=""
ORIGINAL_ARTIFACT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --input) INPUT_DIR="$2"; shift 2 ;;
    --output) OUTPUT_FILE="$2"; shift 2 ;;
    --artifact) ORIGINAL_ARTIFACT="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$INPUT_DIR" || -z "$OUTPUT_FILE" || -z "$ORIGINAL_ARTIFACT" ]]; then
  cat <<'EOF' >&2
Usage:
  aggregator-stub.sh --input <reviewer_results_dir> --output <polisher_input.md> --artifact <original.md>

  --input:    directory containing aw-*.json (each reviewer result)
  --output:   output markdown for polisher input
  --artifact: original PRD/SOP/manuscript draft file
EOF
  exit 1
fi

if [[ ! -d "$INPUT_DIR" ]]; then
  echo "ERROR: input dir not found: $INPUT_DIR" >&2
  exit 1
fi
if [[ ! -f "$ORIGINAL_ARTIFACT" ]]; then
  echo "ERROR: original artifact not found: $ORIGINAL_ARTIFACT" >&2
  exit 1
fi

# ─── aggregate ───
# tmp file 사용 (cross-platform)
AGG_TMP="$TMPDIR/pa-aggregator-$$.json"
trap 'rm -f "$AGG_TMP"' EXIT

echo "[]" > "$AGG_TMP"

# 각 reviewer result 파일 순회
for f in "$INPUT_DIR"/aw-*.json; do
  [[ -f "$f" ]] || continue
  # JSON 유효성 확인 (없으면 jq 사용 권장, alpha는 grep으로 minimal validation)
  if ! grep -q '"reviewer"' "$f" 2>/dev/null; then
    echo "WARN: invalid reviewer result (skipped): $f" >&2
    continue
  fi
  # alpha = jq 없으면 simple concat
  # jq 있으면 더 robust하게 구현 가능 (rc1+ migration)
  cat "$f" >> "$AGG_TMP"
  echo "," >> "$AGG_TMP"
done

# ─── markdown 생성 ───
{
  echo "# Polisher Input (aggregated from 7 active reviewer)"
  echo ""
  echo "Generated by aggregator-stub.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "## Original artifact"
  echo ""
  echo '```markdown'
  cat "$ORIGINAL_ARTIFACT"
  echo '```'
  echo ""
  echo "## Review Aggregation (by dim)"
  echo ""
  echo "각 dim별 점수와 BLOCK/WARN findings:"
  echo ""

  # 각 dim별로 reviewer 결과 합치기 (alpha = 단순 grep, jq 있으면 더 robust)
  for dim in completeness consistency clarity feasibility scope; do
    echo "### Dim: $dim"
    echo ""
    found_any=0
    for f in "$INPUT_DIR"/aw-*.json; do
      [[ -f "$f" ]] || continue
      if grep -q "\"dim\": *\"$dim\"" "$f" 2>/dev/null; then
        reviewer=$(grep -o '"reviewer": *"[^"]*"' "$f" | head -1 | sed 's/"reviewer": *"\(.*\)"/\1/')
        score=$(grep -o '"score": *[0-9]*' "$f" | head -1 | sed 's/"score": *//')
        verdict=$(grep -o '"verdict": *"[^"]*"' "$f" | head -1 | sed 's/"verdict": *"\(.*\)"/\1/')
        echo "- **$reviewer**: score=$score, verdict=$verdict"
        # findings 출력 (alpha = naive grep, rc1+ = jq parse)
        grep -o '"description": *"[^"]*"' "$f" | head -5 | sed 's/"description": *"/  - /' | sed 's/"$//'
        found_any=1
      fi
    done
    [[ $found_any -eq 0 ]] && echo "_(no findings)_"
    echo ""
  done

  echo "## Polish Targets (BLOCK + WARN findings, sorted by location)"
  echo ""
  echo "polisher가 fix해야 할 target list. location 순서 (line N) 로 정렬."
  echo ""
  echo "[alpha stub: BLOCK/WARN findings 추출 + line N 정렬 — Phase 1 T7 구현 시 완성]"
  echo ""
  echo "---"
  echo ""
  echo "## Notes for polisher"
  echo ""
  echo "- 본 input은 aggregator-stub이 생성 (plan-eng-review 1.1A defensive SPOF insurance)"
  echo "- polisher가 본 input을 받으면 reviewer findings 기반으로 original artifact를 patch"
  echo "- output: patched artifact (unified diff stdout 또는 patched file)"
  echo "- output format detect는 SKILL.md (Pass 2 mechanism) 가 처리"

} > "$OUTPUT_FILE"

echo "OK: aggregated $(ls "$INPUT_DIR"/aw-*.json 2>/dev/null | wc -l | tr -d ' ') reviewer results → $OUTPUT_FILE"

# ─── status code ───
# 0 = aggregation 성공
# 1 = input dir 또는 artifact 부재
# 2 = (rc1+) invalid reviewer result fatal
